insert into public.categories (name, slug, sort_order) values
('Industrial Lockers','industrial-lockers',10),('Steel Cupboards','steel-cupboards',20),('Mobile Compactors','mobile-compactors',30),
('Slotted Angle Racks','slotted-angle-racks',40),('Heavy Duty Racks','heavy-duty-racks',50),('Pallet Racking Systems','pallet-racking-systems',60),
('Warehouse Storage Systems','warehouse-storage-systems',70),('File Cabinets','file-cabinets',80),('Industrial Furniture','industrial-furniture',90),
('Customized Storage Solutions','customized-storage-solutions',100)
on conflict (slug) do update set name=excluded.name, sort_order=excluded.sort_order, active=true;

with seed as (
  select * from jsonb_to_recordset($products$[
{"slug":"multi-door-industrial-locker","name":"Multi-Door Industrial Locker","category_slug":"industrial-lockers","short_description":"Compartment-based personal storage for industrial and workforce environments.","description":"A configurable locker system intended to organise personal belongings and issued equipment in shared workplaces.","featured":true,"features":["Individual storage compartments","Door-based organisation","Configurable compartment layout"],"advantages":["Supports orderly shared facilities","Helps separate individual storage"],"applications":["Factories","Warehouses","Staff changing areas"],"accessories":["Label holders","Internal shelves where required"]},
{"slug":"pigeon-hole-locker","name":"Pigeon Hole Locker","category_slug":"industrial-lockers","short_description":"Compact multi-compartment storage for organised item allocation.","description":"A pigeon-hole format locker designed for separating smaller items, documents, or personal effects by user or department.","featured":false,"features":["Multiple individual compartments","Space-conscious layout","Clear compartment organisation"],"advantages":["Simplifies item allocation","Keeps smaller items separated"],"applications":["Offices","Institutions","Industrial facilities"]},
{"slug":"double-door-steel-cupboard","name":"Double Door Steel Cupboard","category_slug":"steel-cupboards","short_description":"Enclosed general-purpose storage for files, supplies, and workplace essentials.","description":"A practical double-door cupboard format for keeping operational materials organised and enclosed within commercial or industrial spaces.","featured":true,"features":["Enclosed storage format","Adjustable internal planning","Double-door access"],"advantages":["Reduces visible clutter","Supports centralised storage"],"applications":["Offices","Stores","Institutions"]},
{"slug":"mechanical-mobile-compactor","name":"Mechanical Mobile Compactor","category_slug":"mobile-compactors","short_description":"Movable high-density storage planned to make better use of floor area.","description":"A mobile compactor configuration that consolidates storage bays and opens an access aisle where required.","featured":true,"features":["Movable storage bays","High-density layout concept","Aisle-on-demand access"],"advantages":["Can improve space utilisation","Supports organised record or material storage"],"applications":["Record rooms","Offices","Institutional archives"],"accessories":["Label holders","Shelf dividers"]},
{"slug":"slotted-angle-shelving-rack","name":"Slotted Angle Shelving Rack","category_slug":"slotted-angle-racks","short_description":"Flexible shelving for cartons, parts, records, and general stores.","description":"A modular shelving format suited to organised storage where shelf arrangement and overall sizing may vary by requirement.","featured":false,"features":["Modular shelving layout","Multiple shelf levels","Configurable bay arrangement"],"advantages":["Adaptable to varied item sizes","Supports systematic stock organisation"],"applications":["Stores","Workshops","Back offices"]},
{"slug":"heavy-duty-industrial-rack","name":"Heavy Duty Industrial Rack","category_slug":"heavy-duty-racks","short_description":"Industrial racking configured for demanding material-storage workflows.","description":"A heavy-duty rack format planned around the stored goods, handling method, bay layout, and available facility space.","featured":true,"features":["Industrial bay configuration","Multi-level storage layout","Requirement-led planning"],"advantages":["Improves vertical space use","Helps structure bulk storage areas"],"applications":["Manufacturing units","Industrial stores","Warehouses"]},
{"slug":"selective-pallet-racking-system","name":"Selective Pallet Racking System","category_slug":"pallet-racking-systems","short_description":"Direct-access pallet storage for structured warehouse operations.","description":"A selective pallet racking layout intended to provide accessible pallet positions arranged around aisle and handling requirements.","featured":true,"features":["Direct pallet-position access","Multi-level warehouse layout","Configurable bay planning"],"advantages":["Supports selective stock access","Organises palletised inventory"],"applications":["Warehouses","Distribution facilities","Manufacturing stores"],"accessories":["Rack protection options","Location labels","Support accessories as required"]},
{"slug":"long-span-warehouse-rack","name":"Long Span Warehouse Rack","category_slug":"warehouse-storage-systems","short_description":"Wide-bay shelving for cartons, bins, and manually handled inventory.","description":"A long-span storage arrangement for items that benefit from broader shelf openings and configurable levels.","featured":false,"features":["Wide shelf bays","Multiple storage levels","Configurable runs"],"advantages":["Supports organised carton storage","Makes use of vertical space"],"applications":["Warehouses","E-commerce stores","Distribution areas"]},
{"slug":"warehouse-storage-rack","name":"Warehouse Storage Rack","category_slug":"warehouse-storage-systems","short_description":"A configurable rack system for structured inventory and material storage.","description":"A general warehouse storage solution that can be planned around inventory type, access needs, and the available floor plan.","featured":false,"features":["Requirement-led layout","Bay-based organisation","Multiple storage levels"],"advantages":["Creates defined storage locations","Supports clearer inventory organisation"],"applications":["Warehousing","Logistics","Commercial stores"]},
{"slug":"four-drawer-filing-cabinet","name":"Four Drawer Filing Cabinet","category_slug":"file-cabinets","short_description":"Drawer-based filing storage for organised workplace records.","description":"A vertical filing cabinet format for grouping and accessing paper records within offices and administrative environments.","featured":false,"features":["Four-drawer format","Vertical filing layout","Document-focused organisation"],"advantages":["Keeps files grouped","Uses a compact floor footprint"],"applications":["Offices","Hospitals","Educational institutions"],"accessories":["File dividers","Label holders"]},
{"slug":"industrial-work-table","name":"Industrial Work Table","category_slug":"industrial-furniture","short_description":"A configurable work surface for production, assembly, and service areas.","description":"An industrial table format that can be configured around the work activity, available space, and storage requirements.","featured":false,"features":["Work-focused layout","Configurable surface and storage arrangement","Industrial application format"],"advantages":["Creates a defined work area","Can combine work and storage functions"],"applications":["Assembly areas","Workshops","Maintenance departments"],"accessories":["Drawer units","Lower shelves","Tool panels where required"]},
{"slug":"custom-storage-system","name":"Custom Storage System","category_slug":"customized-storage-solutions","short_description":"A requirement-led storage configuration planned around your space and workflow.","description":"A tailored storage approach for projects where standard rack, cupboard, locker, or furniture formats do not fully address the operational requirement.","featured":true,"features":["Requirement discovery","Space-led configuration","Combination of suitable storage formats"],"advantages":["Aligns storage with operational needs","Can address unusual spaces or workflows"],"applications":["Factories","Warehouses","Commercial facilities"],"customization_options":["Layout","Dimensions","Storage format","Internal arrangement","Finish and colour options"]}
]$products$) as x(slug text,name text,category_slug text,short_description text,description text,featured boolean,features jsonb,advantages jsonb,applications jsonb,accessories jsonb,customization_options jsonb)
)
insert into public.products (category_id,slug,name,short_description,description,featured,active,primary_image,gallery,sizes,specifications,features,advantages,applications,accessories,customization_options,sort_order)
select c.id,s.slug,s.name,s.short_description,s.description,s.featured,true,'/images/products/product-placeholder.svg',jsonb_build_array('/images/products/product-placeholder.svg'),
  '[{"label":"Custom sizing","notes":"Available in multiple/custom sizes"}]'::jsonb,
  '[{"label":"Configuration","value":"Planned according to the selected product and application"},{"label":"Available sizes","value":"Available in multiple/custom sizes"}]'::jsonb,
  coalesce(s.features,'[]'),coalesce(s.advantages,'[]'),coalesce(s.applications,'[]'),coalesce(s.accessories,'[]'),
  coalesce(s.customization_options,'["Dimensions","Internal configuration","Finish and colour options"]'), row_number() over(order by c.sort_order,s.name)::integer * 10
from seed s join public.categories c on c.slug=s.category_slug
on conflict (slug) do update set category_id=excluded.category_id,name=excluded.name,short_description=excluded.short_description,description=excluded.description,
featured=excluded.featured,active=true,primary_image=excluded.primary_image,gallery=excluded.gallery,sizes=excluded.sizes,specifications=excluded.specifications,
features=excluded.features,advantages=excluded.advantages,applications=excluded.applications,accessories=excluded.accessories,customization_options=excluded.customization_options,sort_order=excluded.sort_order;
