import type { Metadata } from "next";
import { Footer } from "@/components/layout/footer";
import { Header } from "@/components/layout/header";
import { TopBar } from "@/components/layout/top-bar";
import { activeProducts, getProductBySlug } from "@/data/products";

export const metadata: Metadata = { title: "Request a Quote", description: "Share your industrial storage requirement with Shakshi Enterprises for product and quotation guidance." };
type Props = { searchParams: Promise<{ product?: string }> };
const fields = [
  { name: "fullName", label: "Full Name", type: "text", required: true }, { name: "companyName", label: "Company Name", type: "text" },
  { name: "mobile", label: "Mobile Number", type: "tel", required: true }, { name: "email", label: "Email", type: "email", required: true },
  { name: "city", label: "City", type: "text" }, { name: "state", label: "State", type: "text" },
  { name: "variant", label: "Size / Variant", type: "text" }, { name: "quantity", label: "Quantity", type: "number" },
];

export default async function RequestQuotePage({ searchParams }: Props) { const selected = getProductBySlug((await searchParams).product ?? ""); return <><TopBar /><Header /><main><section className="bg-neutral-950 px-4 py-14 text-white sm:px-6 sm:py-20 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[0.24em] text-amber-400">Business enquiry</p><h1 className="mt-4 text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">Request a Quote</h1><p className="mt-5 max-w-2xl leading-7 text-neutral-300">Tell us what you need. This form is currently a frontend preview and does not submit or store information yet.</p></div></section><section className="bg-neutral-100 px-4 py-14 sm:px-6 sm:py-20 lg:px-8"><form className="mx-auto max-w-4xl border border-neutral-200 bg-white p-6 sm:p-10" aria-describedby="form-status"><div className="grid gap-6 sm:grid-cols-2">{fields.map((field) => <label className="grid gap-2 text-sm font-semibold text-neutral-800" key={field.name}>{field.label}{field.required && <span className="sr-only">required</span>}<input className="h-12 border border-neutral-300 px-4 font-normal outline-none focus:border-amber-500" min={field.type === "number" ? 1 : undefined} name={field.name} required={field.required} type={field.type} /></label>)}<label className="grid gap-2 text-sm font-semibold text-neutral-800 sm:col-span-2">Product Required<select className="h-12 border border-neutral-300 bg-white px-4 font-normal outline-none focus:border-amber-500" defaultValue={selected?.slug ?? ""} name="product"><option value="">Select a product</option>{activeProducts.map((product) => <option key={product.slug} value={product.slug}>{product.name}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold text-neutral-800 sm:col-span-2">Requirement / Message<textarea className="min-h-36 border border-neutral-300 p-4 font-normal outline-none focus:border-amber-500" name="message" placeholder="Share your space, application, size, quantity, or other requirement." /></label></div><div className="mt-8 border-t border-neutral-200 pt-6"><button className="min-h-12 cursor-not-allowed bg-neutral-300 px-7 text-sm font-bold text-neutral-600" disabled type="button">Submit Enquiry</button><p className="mt-4 text-sm leading-6 text-neutral-500" id="form-status">Submission will be enabled after the secure enquiry backend is connected. No information entered here is currently sent or stored.</p></div></form></section></main><Footer /></>; }
